### ISSUE TITLE
NPE on normalizePhoneNumber

### ISSUE THREAD

**Issue by akashpathak** [PrivacyStreams/PrivacyStreams#13]
Hi,

This issue is specific to Xiaomi device may be, because I did not get this on samsung or nexus devices.

Brand: Xiaomi
Model: Redmi Note 4
Orientation: Portrait
RAM free: 936.84 MB
Disk free: 8.15 GB
Version: 7.0
Orientation: Portrait
Rooted: No

I am using: android-sdk:0.1.7 version of the library.

Below is crash logs.

04-09 21:38:50.390 9948-9948/packagename D/PrivacyStreams: Trying to evaluate query {SMSMessageListProvider[] --> ByFieldStreamSorter[timestamp] --> PredicateFilter[FieldCompareOperator[$field_gt, timestamp, 0]] --> StreamReverser[] --> PStreamCollector[StreamListCollector[], []]}. Purpose {Social: Finding sms logs} Required Permissions: [android.permission.READ_SMS]
04-09 21:38:50.393 9948-9948/packagename D/PrivacyStreams: Permission granted, evaluating...
04-09 21:38:50.405 9948-9948/packagename D/PrivacyStreams: Evaluated.
04-09 21:38:50.437 9948-10037/packagename E/AndroidRuntime: FATAL EXCEPTION: Thread-19 Process: packagename , PID: 9948 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
 at io.github.privacystreams.utils.CommunicationUtils.normalizePhoneNumber(CommunicationUtils.java:9)
at io.github.privacystreams.communication.SMSMessageListProvider.provide(SMSMessageListProvider.java:39)
at io.github.privacystreams.core.PStreamProvider$1.run(PStreamProvider.java:19)

Let me know if you need more info. This issue is reproducable 100% of the time.

Thanks

**Comment by ylimit** [comment]
It seems one (or more) of the SMS messages does not have a phone number. Can you please test it with several manually-crafted SMS messages?

**Comment by akashpathak** [comment]
Hi,

So I tried to create a message with no number in the 'To' field, but the app doesnt allow me to do that. It does not even save it as a draft without a number in or contact name in the field. I went through all the logs in that phone, to see if a specific phone number came with no phone number, but that is not the case. They all have either a contact name or phone number attached with them.

Are you able to catch this error and print stack trace so it might be helpful to pinpoint the issue?

**Comment by akashpathak** [comment]
So I was able to test this further. The crash happens if the message is in draft mode. This does not happen on other phones, maybe just the Xiaomi messaging app that is causing this issue.

**Comment by ylimit** [comment]
I see. So we need to handle the case where the phone number is null. Will fix it soon.

**Comment by ylimit** [comment]
Just added a line in `CommunicationUtils.normalizePhoneNumber` method to check null pointers. See commit 7c2959741c9bc70d1c0b61e37d5a3cdf205b9fdc

**Comment by akashpathak** [comment]
Thanks, just saw that. Will you be making a release anytime soon? I would like to upgrade the library when you release.
