### ISSUE TITLE
Exception when launch Monitor IM

### ISSUE THREAD

**Issue by rupas385** [PrivacyStreams/PrivacyStreams#22]
Hi,
Im testing this library but all times I get this exception. Any help?

this is my code:
`
@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public static void monitorMessagesIM(Context context){
         UQI uqi;
         Purpose purpose;
         uqi = new UQI(context);
         purpose = Purpose.TEST("Examples");

        uqi.getData(Message.asUpdatesInIM(), purpose) // get a live stream of IM message updates.
                .forEach(new Callback<Item>() {
                    @Override
                    protected void onInput(Item input) { // callback with each item.
                        String type = input.getValueByField("type"); // get the value of "type" field.
                        String content = input.getValueByField("content"); // get the value of "content" field.
                        String contact = input.getValueByField("contact"); // get the value of "contact" field.
                        if ("sent".equals(type)) {
                            System.out.println("Sent a message to " + contact + ": " + content);
                        }
                        else if ("received".equals(type)) {
                            System.out.println("Received a message from " + contact + ": " + content);
                        }
                    }
                });
    }`

`java.lang.RuntimeException: Unable to start activity ComponentInfo{me.fpy/me.hawkshaw.ui.activities.HomeActivity}: i.a.a.e: Subscriber class d.b.a.b.m.a.b and its super classes have no public methods with the @Subscribe annotation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: i.a.a.e: Subscriber class d.b.a.b.m.a.b and its super classes have no public methods with the @Subscribe annotation
        at i.a.a.m.a(:67)
        at i.a.a.c.b(:136)
        at d.b.a.b.k.a(:95)
        at d.b.a.b.g.g(:27)
        at d.b.a.b.c.a(:26)
        at d.b.a.b.b.a(:23)
        at d.b.a.b.l.a(:121)
        at d.b.a.b.f.a(:60)
        at d.b.a.b.f.d(:551)
        at me.hawkshaw.utils.e.a(:33)
        at me.hawkshaw.ui.activities.HomeActivity.onCreate(:37)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)`

**Comment by rupas385** [comment]
Solved migrating project to AndroidX
